version: '3.7'

services:
  dokuwiki:
    image: bitnami/dokuwiki:latest
    container_name: dokuwiki
    ports:
      - "8080:8080"
    environment:
      - DOKUWIKI_USERNAME=name
      - DOKUWIKI_PASSWORD=password
      - DOKUWIKI_FULL_NAME=yourname
      - DOKUWIKI_EMAIL=yourmail
    volumes:
      - dokuwiki_data:/bitnami/dokuwiki

volumes:
  dokuwiki_data:
    driver: local
