version: '3.7'

services:
  dokuwiki:
    image: bitnami/dokuwiki:latest
    container_name: dokuwiki
    ports:
      - "8081:8080"
    environment:
      - DOKUWIKI_USERNAME=fvillain
      - DOKUWIKI_PASSWORD=newb313!
      - DOKUWIKI_FULL_NAME=fvillain
      - DOKUWIKI_EMAIL=helloitsramil@gmail.com
    volumes:
      - dokuwiki_data:/bitnami/dokuwiki

volumes:
  dokuwiki_data:
    driver: local
